brand_strategy_task:
  description: >
    Analyze the provided raw content from "{source_filename}" and develop a comprehensive brand strategy approach aligned with the "Syntax & Empathy" brand foundation.
    
    {%- if title %}
    Article Title: {title}
    {%- endif %}
    {%- if context %}
    Article Context: {context}
    {%- endif %}
    {%- if summary %}
    Article Summary: {summary}
    {%- endif %}
    {%- if brand %}
    Target Brand: {brand}
    {%- endif %}
    {%- if personas %}
    Target Personas: {personas}
    {%- endif %}
    {%- if required_sections %}
    Required Sections: {required_sections}
    {%- endif %}
    {%- if notes %}
    Special Instructions: {notes}
    {%- endif %}
    
    Raw content to analyze:
    {raw_content}
    
    Your responsibilities include:
    1. Use the Brand Style Guide tool to access the complete brand foundation, target personas, and voice characteristics
    2. Analyze raw content to identify which of the three content pillars it aligns with (Prompt Engineering Fundamentals, UX Workflow Integration, Human-AI Design Partnership)
    3. Determine appropriate target personas from: Strategic Sofia, Adaptive Alex, Curious Casey, Analytical Morgan, Systematic Sam
    4. Apply the brand voice characteristics: Methodical Experimenter, Practical Educator & Translator, Transparent Practitioner, Ethical Realist
    5. Ensure content reflects brand values: transparency, curiosity, continuous evolution, practical integrity
    6. Identify opportunities to include real examples, failure documentation, iteration counts, and practical implementation guidance
    7. Suggest structure that includes ethical considerations woven throughout (not as afterthoughts)
    8. Recommend how to demonstrate transparency through metrics, revision processes, and honest documentation
    9. Ensure content addresses specific user agency, bias detection, and responsible AI usage
    {%- if required_sections %}
    10. Ensure the structure includes these required sections: {required_sections}
    {%- endif %}
    
    Use the Brand Style Guide tool extensively to access the full brand foundation and persona documentation.
    
    CRITICAL: The brand voice uses first person because it represents the author's personal experience and expertise. DO NOT write as "I" in the content - that would be fabricating the author's personal experiences. Instead:
    - Write up to the point where "I" would be needed
    - Use [AUTHOR: personal experience needed] or [TODO: add personal example] annotations
    - Only use supplied materials and documented examples
    - Never fabricate personal experiences, testing results, or "I did this" statements
    
    Output should include specific voice guidelines, content pillar alignment, persona targeting, and practical implementation strategy.
  expected_output: >
    A comprehensive brand strategy document containing:
    - Analysis of the raw content's themes and potential
    - Brand voice and tone guidelines for this article
    - Key messaging pillars and themes to emphasize
    - Target audience considerations and positioning strategy
    - Content differentiation strategy
    - Specific brand guidelines and requirements for the writing team
    - Recommendations for structuring and enhancing the raw content
    - Success metrics and brand alignment criteria
    Formatted as structured markdown without code blocks
  agent: brand_strategist

feedback_collection_task:
  description: >
    Solicit comprehensive feedback on the completed article from "{source_filename}" to drive continuous improvement and ensure content meets professional standards.
    
    You are provided with the final article content that has been published or is ready for publication.
    
    Your feedback collection responsibilities:
    1. Create a structured feedback survey that asks specific, actionable questions about:
       - Content clarity and understandability
       - Practical usefulness and applicability
       - Technical accuracy and completeness
       - Brand voice consistency and authenticity
       - Audience alignment and relevance
       - Engagement and readability
       - Areas for improvement or expansion
    
    2. Design feedback questions that generate actionable insights:
       - What sections were most/least helpful and why?
       - Which examples or explanations need more clarity?
       - What additional information would make this more useful?
       - How does this content compare to similar resources you've seen?
       - What would make you more likely to implement these suggestions?
    
    3. Create multiple feedback collection methods:
       - Formal feedback survey with structured questions
       - Informal feedback prompts for social media/email responses
       - Specific questions for different audience segments
       - Follow-up questions for deeper insights
    
    4. Establish feedback analysis framework:
       - Categories for organizing feedback (clarity, usefulness, accuracy, etc.)
       - Scoring systems for quantifiable feedback
       - Process for identifying patterns and trends
       - Method for translating feedback into content improvements
    
    5. Generate actionable recommendations:
       - Specific improvements for future content
       - Content gaps to address in upcoming articles
       - Structural improvements for better engagement
       - Brand voice adjustments based on audience response
    
    Your approach should be professional, respectful, and focused on continuous improvement rather than criticism.
    
    IMPORTANT: You are collecting feedback on completed content, not conducting research. Focus on understanding how well the content serves its intended purpose and audience.
  expected_output: >
    A comprehensive feedback collection package containing:
    - Structured feedback survey with 8-12 specific questions
    - Informal feedback prompts for different channels
    - Feedback analysis framework and scoring system
    - Instructions for feedback collection and analysis
    - Template for organizing and categorizing responses
    - Recommendations for implementing feedback-driven improvements
    - Metrics for measuring content effectiveness
    - Follow-up plan for ongoing feedback collection
    Formatted as structured markdown with clear instructions
  agent: feedback_collector

writing_task:
  description: >
    Transform the raw content from "{source_filename}" into a compelling article that embodies the "Syntax & Empathy" brand voice and serves the target UX professional audience.
    
    {%- if title %}
    Target Title: {title}
    {%- endif %}
    {%- if context %}
    Article Context: {context}
    {%- endif %}
    {%- if summary %}
    Article Summary: {summary}
    {%- endif %}
    {%- if brand %}
    Brand: {brand}
    {%- endif %}
    {%- if personas %}
    Target Personas: {personas}
    {%- endif %}
    {%- if required_sections %}
    Required Article Sections: {required_sections}
    {%- endif %}
    {%- if notes %}
    Special Writing Instructions: {notes}
    {%- endif %}
    
    Raw content to transform:
    {raw_content}
    
    Article requirements:
    1. Embody the brand voice characteristics: Methodical Experimenter, Practical Educator & Translator, Transparent Practitioner, Ethical Realist
    2. Include real examples from testing and experimentation (not theoretical scenarios)
    3. Document both successes and failures with equal transparency
    4. Provide step-by-step implementation guidance with specific tools and techniques
    5. Address ethical considerations throughout (user agency, bias detection, responsible AI use)
    6. Include iteration counts, revision processes, or other transparency metrics where relevant
    7. Write for the identified target personas with appropriate experience-level considerations
    8. Align content with the relevant content pillar (Prompt Engineering, UX Workflows, or Human-AI Partnership)
    9. Use transition phrases like "This connects to a pattern I've seen before..." and "The implementation details matter here because..."
    10. End with actionable next steps, testing suggestions, or exploratory questions
    11. Include practical examples, downloadable resources, or templates where appropriate
    12. Maintain conversational warmth while being technically precise
    13. Frame content as ongoing discovery rather than final answers
    
    The article should demonstrate the brand's commitment to transparency, practical integrity, and evidence-based recommendations.
    
    CRITICAL WRITING CONSTRAINTS:
    - DO NOT write as "I" - this fabricates the author's personal experiences
    - Use supplied materials only - do not invent examples, testing results, or personal anecdotes
    - When personal experience would strengthen the content, use annotations like:
      * [AUTHOR: add personal testing example here]
      * [TODO: include specific results from your experiment with X]
      * [AUTHOR: describe your experience with Y tool]
    - Focus on documented techniques, research findings, and practical guidance
    - Frame advice as "designers can" or "this approach enables" rather than "I found"
    
    Remember: The brand voice documentation uses "I" to describe the author's authentic voice - you are writing content that matches that voice without fabricating personal experiences.
  expected_output: >
    A complete, publication-ready article containing:
    - Compelling headline that captures attention
    - Engaging introduction that hooks readers
    - Well-structured main content with clear sections
    - Enhanced content from the raw material with additional insights
    - Supporting data, examples, and research findings
    - Strong conclusion with clear takeaways
    - Proper formatting for newsletter/Substack publication
    - Consistent brand voice throughout
    - Word count appropriate for the platform (1500-3000 words)
    Formatted as clean markdown ready for publication
  agent: article_writer

seo_optimization_task:
  description: >
    Optimize the article for search engines within the AI-UX design niche while maintaining the authentic "Syntax & Empathy" brand voice.
    
    Optimization requirements:
    1. Target relevant keywords: "prompt engineering for UX", "AI tools for designers", "ethical AI in UX", "human-AI collaboration", "AI workflow integration", "UX AI best practices"
    2. Optimize headlines and subheadings for both search and the target UX professional audience
    3. Structure content for featured snippets on technical UX questions
    4. Ensure proper keyword integration that sounds natural to experienced UX professionals
    5. Optimize for professional development and educational search queries
    6. Create meta descriptions that appeal to designers seeking practical AI integration guidance
    7. Optimize for newsletter and Substack-specific SEO considerations
    8. Maintain the brand's transparent and practical voice throughout optimization
    9. Ensure technical accuracy is preserved during optimization
    10. Structure content for easy scanning by busy UX professionals
    11. Include relevant long-tail keywords that address specific implementation challenges
    12. Optimize for both individual designers and team leads searching for AI adoption strategies
    
    Use SEO analysis tools while ensuring content remains valuable to the target personas and maintains brand authenticity.
  expected_output: >
    An SEO-optimized version of the article including:
    - Optimized headline and subheadings
    - Strategic keyword integration throughout content
    - Improved content structure and formatting
    - Meta description and article summary
    - SEO recommendations and implementation notes
    - Newsletter-specific optimization suggestions
    - Performance metrics and optimization targets
    - Maintained brand voice and content quality
    Formatted as publication-ready markdown with SEO enhancements
  agent: seo_specialist

editing_task:
  description: >
    Review, refine, and finalize the article to ensure it meets the highest professional standards of the "Syntax & Empathy" brand and serves the UX professional audience effectively.
    
    Professional editing responsibilities:
    1. Verify brand voice consistency across all four characteristics: Methodical Experimenter, Practical Educator & Translator, Transparent Practitioner, Ethical Realist
    2. Ensure examples come from real experience and testing (not theoretical scenarios)
    3. Verify that both successes and failures are documented with equal transparency
    4. Check that ethical considerations are woven throughout the content, not added as afterthoughts
    5. Ensure content appropriately serves the target personas identified in the brand strategy
    6. Verify alignment with the relevant content pillar (Prompt Engineering, UX Workflows, or Human-AI Partnership)
    7. Check that practical implementation guidance is specific and actionable
    8. Ensure bias detection and responsible AI usage are addressed practically
    9. Verify that transparency metrics (iteration counts, revision processes, etc.) are included where relevant
    10. Check grammar, spelling, and punctuation while maintaining conversational warmth
    11. Ensure proper formatting for newsletter/Substack publication
    12. Conduct comprehensive fact-checking of all claims and technical accuracy
    13. Check that content ends with actionable next steps or exploratory questions
    14. Ensure content demonstrates the brand's commitment to practical integrity and continuous learning
    15. Perform multi-dimensional quality assessment using professional standards
    16. Verify technical accuracy and validate all factual claims
    17. Ensure content meets enterprise-level quality standards
    
    Use the Content Quality Analysis tool to perform comprehensive quality assessment.
    Use the Fact Checking tool to verify all claims and technical statements.
    
    The final output should authentically represent the "Syntax & Empathy" brand while providing genuine value to UX professionals integrating AI into their work.
    
    FINAL EDITING REQUIREMENTS:
    - Verify NO fabricated personal experiences or "I did this" statements
    - Ensure all personal anecdotes are properly annotated as [AUTHOR: add personal context]
    - Check that examples come from supplied materials, not invented scenarios
    - Confirm the content maintains the brand voice without impersonating the author
    - Flag any sections requiring the author's personal input or experience
    - Conduct comprehensive fact-checking of all technical claims
    - Ensure content meets professional-grade quality standards
    - Verify multi-dimensional quality assessment shows EXCELLENT or GOOD ratings
  expected_output: >
    A final, publication-ready article that includes:
    - Error-free grammar, spelling, and punctuation
    - Consistent brand voice and messaging
    - Verified facts and accurate citations with comprehensive fact-checking report
    - Multi-dimensional quality assessment showing professional standards
    - Optimized content flow and readability
    - Proper Substack formatting and structure
    - Quality assurance report with any changes made
    - Final recommendations for publication
    - Performance expectations and success metrics
    - Fact-checking validation report
    - Professional quality analysis report
    Formatted as polished markdown ready for immediate publication
  agent: editor